### ISSUE TITLE
An error occurred while verifying the token

### ISSUE THREAD

**Issue by vandykew** [elie195/duo_provider#19] opened 2018-03-26 14:13 UTC
I had this working and all of a sudden it started giving this error, The DUO auth is successful but its providing this error "An error occurred while verifying the token"

**Comment by elie195** [comment] 2018-03-26 18:01
Thanks for the report. Could you please include any relevant lines from your owncloud.log file? And do a quick double-check to confirm your settings are correct for the Duo plugin in ownCloud Settings? Thanks.

**Comment by vandykew** [comment] 2018-03-26 18:46
The duo settings look good, Below is the line from the owncloud.log

{"reqId":"mWrO28pTHN5Ior9Mmn3T","level":3,"time":"2018-03-26T14:10:33+00:00","remoteAddr":"192.168.77.50","user":"John.VanDyke","app":"index","method":"POST","url":"\/owncloud\/index.php\/login\/challenge\/duo?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function Duo\\\\alert()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/duo\\\/lib\\\/Web.php(104): Duo\\\\Web::parseVals('Lxojii17PymT3CP...', 'AUTH|Sm9obi5WYW...', 'AUTH', 'DIGQMMV9TRZSP2Y...', NULL)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/duo\\\/lib\\\/Service\\\/DuoService.php(159): Duo\\\\Web::verifyResponse('DIGQMMV9TRZSP2Y...', 'Lxojii17PymT3CP...', '2308c06b1c14109...', 'AUTH|Sm9obi5WYW...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/duo\\\/lib\\\/Provider\\\/DuoProvider.php(99): OCA\\\\Duo\\\\Service\\\\DuoService->validateChallenge(Object(OC\\\\User\\\\User), 'AUTH|Sm9obi5WYW...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(158): OCA\\\\Duo\\\\Provider\\\\DuoProvider->verifyChallenge(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/TwoFactorChallengeController.php(172): OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->verifyChallenge(*** sensitive parameters replaced ***)\\n#5 [internal function]: OC\\\\Core\\\\Controller\\\\TwoFactorChallengeController->solveChallenge(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\TwoFactorChallengeController), 'solveChallenge')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\TwoFactorChallengeController), 'solveChallenge')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('TwoFactorChalle...', 'solveChallenge', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(929): OC\\\\Route\\\\Router->match('\\\/login\\\/challeng...')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/duo\\\/lib\\\/Web.php\",\"Line\":40}"}

**Comment by elie195** [comment] 2018-03-26 18:52
Thanks for the log. I’m not able to reproduce this on my end, so it might be a little difficult to debug. 

What ownCloud version are you using? And what Duo plugin version? Thanks.

**Comment by vandykew** [comment] 2018-03-26 18:55
Owncloud 10.0.4 

Duo plugin 2.4.0 

It seamed like this just started today

**Comment by elie195** [comment] 2018-03-26 19:00
Thanks. I’m checking the underlying code to see whether the issue is in the ownCloud 2FA framework, or if it’s in the Duo plugin, since it’s not clear to me from the log output. 

In the meantime, could you please try the following?

- Regenrate your “AKEY” setting. You can either auto-generate a new one, or run the python command in the README to manually generate a new one, and use that value
- Remove/add the Duo plugin from ownCloud in an attempt to reinstall it

**Comment by vandykew** [comment] 2018-03-26 19:31
Ok I did both of those, and the issue still happens

**Comment by elie195** [comment] 2018-03-26 20:08
Ok it looks like ownCloud isn’t able to verify the signature that’s being generated by Duo. This is all done between the Duo web framework and the Two-factor Authentication framework in ownCloud.

I verified that the Duo plugin is using the latest versions of the Duo web/PHP framework, so I believe the issue may be due to a client-side issue. 

Could you try using another client, as well as another browser in incognito/private mode?

**Comment by vandykew** [comment] 2018-03-26 20:25
Sure, 

I have tried on a new PC with Chrome and Firefox both in incognito mode and still have the same issue

**Comment by elie195** [comment] 2018-03-26 20:47
Thanks for trying. I’ll need to research this a bit further on the Duo Web/2FA framework side. Feel free to add any additional relevant info in the meantime. 

Just in-case this turns relevant, would you be open to installing a debug build of the Duo plugin? I’m hoping this won’t be needed but the idea is to increase logging verbosity on this build to get some further insight into the issue.

**Comment by elie195** [comment] 2018-03-27 02:12
One other thing you can verify is the system time on the ownCloud server and your clients and make sure they are synced.

**Comment by fnetto** [comment] 2018-07-22 22:56
Was this ever resolved?  I am having same issue.

**Comment by elie195** [comment] 2018-07-23 02:32
I was able to reproduce this issue by setting the ownCloud server time to a few minutes ahead of the actual time (I tried a few hours initially, but that wouldn't even get to the Duo prompt).

**Please make sure your ownCloud server has the correct date/time set (preferably synced to an NTP server)**. I'm going to close this issue for now, but if you're still having issues, please reply with:

- server logs (owncloud.log) with sensitive info such as "SKEY" removed
- ownCloud version
- PHP version
- Duo plugin version

**Closed as completed by elie195** 2018-07-23 02:32 UTC
